modLoader="javafml"
loaderVersion="[25,)"

[[mods]]
modId="torchbowmod"
version="${version}"
displayName="TorchBowMod"
updateJSONURL="https://raw.githubusercontent.com/noriokun4649/TorchBowMod/master/update.json"
credits="noriokun4649"
authors="noriokun4649"
description="Adds a TorchBow."
certificateFingerprint="234565433456778654"

[[dependencies.torchbowmod]]
    modId="forge"
    mandatory=true
    versionRange="[25,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.torchbowmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.2]"
    ordering="NONE"
    side="BOTH"